"""Configuration constants for the Pi webcam RTSP streamer."""

# Camera
VIDEO_DEVICE = "/dev/video0"
INPUT_FORMAT = "mjpeg"  # Lifecam HD-5000 outputs MJPEG natively

# Resolution presets
RESOLUTION_PRESETS = {
    "720p15": {"width": 1280, "height": 720, "fps": 15, "bitrate": "1500k", "keyframe_interval": 30},
    "480p30": {"width": 640, "height": 480, "fps": 30, "bitrate": "1000k", "keyframe_interval": 60},
}
DEFAULT_RESOLUTION = "720p15"

# Encoding
VIDEO_CODEC = "libx264"
PRESET = "ultrafast"
TUNE = "zerolatency"

# RTSP (mediamtx)
RTSP_PORT = 8554
STREAM_NAME = "stream"
MEDIAMTX_BIN = "mediamtx"
MEDIAMTX_CONFIG = "mediamtx.yml"

# Authentication (used for both RTSP stream and web UI)
AUTH_USERNAME = "admin"
AUTH_PASSWORD = "password"

# SSL (self-signed cert generated by setup.sh)
SSL_CERTFILE = "cert.pem"
SSL_KEYFILE = "key.pem"

# Status page
STATUS_PORT = 8080
